<?php
include("wpHash.php");
include("Header.php");
$wList = file_get_contents("wList.txt");
$wList = explode("\n",$wList);
echo $white;
echo base64_decode("CiAgICAgICAgICAgICAgICAgICAuLm9vJDAwb29vLi4gICAgICAgICAgICAgICAgICAgIC4ub29vMDAkb28uLgogICAgICAgICAgICAgICAgLm8kJCQkJCQkJCQnICAgICAgICAgICAgICAgICAgICAgICAgICAnJCQkJCQkJCQkby4KICAgICAgICAgICAgIC5vJCQkJCQkJCQkIiAgICAgICAgICAgICAuICAgLiAgICAgICAgICAgICAgIiQkJCQkJCQkJG8uCiAgICAgICAgICAgLm8kJCQkJCQkJCQkfiAgICAgICAgICAgICAvJCAgICRcICAgICAgICAgICAgICB+JCQkJCQkJCQkJG8uCiAgICAgICAgIC57JCQkJCQkJCQkJCQuICAgICAgICAgICAgICAkXF9fXy8kICAgICAgICAgICAgICAgLiQkJCQkJCQkJCQkfS4KICAgICAgICBvJCQkJCQkJCQkJCQkOCAgICAgICAgICAgICAgLiQkJCQkJCQuICAgICAgICAgICAgICAgOCQkJCQkJCQkJCQkJG8KICAgICAgICQkJCQkJCQkJCQkJCQkJCAgICAgICAgICAgICAgJCQkJCQkJCQkICAgICAgICAgICAgICAgJCQkJCQkJCQkJCQkJCQkCiAgICAgIG8kJCQkJCQkJCQkJCQkJCQuICAgICAgICAgICAgIG8kJCQkJCQkbyAgICAgICAgICAgICAgLiQkJCQkJCQkJCQkJCQkJG8KICAgICAgJCQkJCQkJCQkJCQkJCQkJCQuICAgICAgICAgICBveyQkJCQkJCR9byAgICAgICAgICAgIC4kJCQkJCQkJCQkJCQkJCQkJAogICAgIF4kJCQkJCQkJCQkJCQkJCQkJCQuICAgICAgICAgSiQkJCQkJCQkJCQkTCAgICAgICAgICAuJCQkJCQkJCQkJCQkJCQkJCQkXgogICAgICEkJCQkJCQkJCQkJCQkJCQkJCQkJG9vLi5vbyQkJCQkJCQkJCQkJCQkJCQkb28uLm9vJCQkJCQkJCQkJCQkJCQkJCQkJCQkIQogICAgIHskJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkfQogICAgIDYkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkPwogICAgICckJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJwogICAgICBvJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCRvCiAgICAgICAkJCQkJCQkJCQkJCQkJDsnfmBeWSQkJDdeJydvJCQkJCQkJCQkJCRvJydeWSQkJDdeYH4nOyQkJCQkJCQkJCQkJCQkJAogICAgICAgJyQkJCQkJCQkJCQkJyAgICAgICBgJCcgICAgYCckJCQkJCQkJCQnICAgICBgJCcgICAgICAgJyQkJCQkJCQkJCQkJCcKICAgICAgICAhJCQkJCQkJCQkNyAgICAgICAgICEgICAgICAgJyQkJCQkJCQnICAgICAgICEgICAgICAgICBWJCQkJCQkJCQkIQogICAgICAgICBebyQkJCQkJCEgICAgICAgICAgICAgICAgICAgJyQkJCQkJyAgICAgICAgICAgICAgICAgICAhJCQkJCQkb14KICAgICAgICAgICBeJCQkJCQiICAgICAgICAgICAgICAgICAgICAkJCQkJCAgICAgICAgICAgICAgICAgICAgIiQkJCQkXgogICAgICAgICAgICAgJ28kJCRgICAgICAgICAgICAgICAgICAgIF4kJCQnICAgICAgICAgICAgICAgICAgICckJCRvJwogICAgICAgICAgICAgICB+JCQkLiAgICAgICAgICAgICAgICAgICAkJCQuICAgICAgICAgICAgICAgICAgLiQkJH4KICAgICAgICAgICAgICAgICAnJDsuICAgICAgICAgICAgICAgICAgYCQnICAgICAgICAgICAgICAgICAgLjskJwogICAgICAgICAgICAgICAgICAgICcuICAgICAgICAgICAgICAgICAgISAgICAgICAgICAgICAgICAgIC5g");
echo "\n";
echo "			     $yellow| $green WP Hash cracker v1.0 $yellow|              \n";
echo "			        $yellow| $green Coded by MrSqar $yellow|              \n";
echo $end;
echo "\n";
echo $green;
echo "	[+] Enter WP hash : ";
$Hash = fgets(STDIN,1024);
$Hash = trim($Hash);
echo "\n";
echo $yellow."	[~] Wait ....\n";
foreach($wList as $wList2){
$wList2 = trim($wList2);
$wp_hasher = new PasswordHash(16, true);
$Found = false;
if($wp_hasher->CheckPassword($wList2, $Hash)) {
	echo "	[+] Yes password is correct : $wList2\n" ; 	
$Found = null;
} else {
}
}


